# $ cp ~/.config/alacritty/local.macos.toml ~/.config/alacritty/local.toml

[window]
# https://github.com/alacritty/alacritty/issues/7637#issuecomment-1896162182
option_as_alt = "Both"

[font]
size = 15.0
# size = 16.0

[keyboard]
bindings = [
  # Alacritty + MacOS + Karabiner Elements - Home/End support
  # https://github.com/alacritty/alacritty/issues/474#issuecomment-338803299
  { key = "Left", mods = "Command", chars = "\u001BOH", mode = "AppCursor" },  # Home
  { key = "Right", mods = "Command", chars = "\u001BOF", mode = "AppCursor" }, # End
]
